name: Build Kernel

on:
  #push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup timezone
        uses: szenius/set-timezone@master
        with:
          timezoneLinux: "Asia/Jakarta"

      - name: Run standard build script
        run: |
          sudo apt-get install device-tree-compiler
          export KBUILD_BUILD_USER=mahiroo
          export KBUILD_BUILD_HOST=android-build
          source boled.sh
          echo "ZIPNAME=${ZIPNAME}" >> $GITHUB_ENV

      - name: Upload standard artifact
        uses: actions/upload-artifact@main
        with:
          name: standard-artifact
          path: ${{ env.ZIPNAME }} 

      - name: Create Telegram caption
        run: |
          BUILD_DATE="$(date '+%H:%M %d/%m/%Y')"
          HEAD="$(git rev-parse HEAD)"
          HEAD_COMMIT="https://github.com/Yuddciel/Oplus/commit/$HEAD"
          echo -e "${BUILD_DATE}\n\n${HEAD_COMMIT}" > caption.txt

      - name: Upload standard build to Telegram
        run: |
          caption=$(<caption.txt)
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
          -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -F document=@"${{ env.ZIPNAME }}" \
          -F caption="${caption}"
          
